### ISSUE TITLE
role: the implementation

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/metrics-export-role#6]
We need to implement the role based on [cartridge-metrics-role](https://github.com/tarantool/cartridge-metrics-role). The key differences:

1. We implement only `prometheus`/`json` format, no need in the `health` format.
2. The role should support only Tarantool 3.
3. The implementation is based on the [http](https://github.com/tarantool/http) module. See [as example](https://www.tarantool.io/en/doc/latest/book/monitoring/getting_started/#collecting-http-metrics) , and [an another example](https://github.com/tarantool/metrics/blob/master/example/prometheus_export.lua).

The expected configuration format:
```yaml
roles.metrics-export:
  http:
  - listen: localhost:8081
    endpoints:
    - path: '/path_for_json_metrics'
      format: 'json'
    - path: '/path_for_prometheus_metrics'
      format: 'prometheus'
```

The implementation should be covered with some base integration and unit-tests.
